apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-lgxn
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-lgxn
    app.kubernetes.io/part-of: tkrw-pr714-0075-0057-app
  name: devfile-sample-lgxn
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-lgxn
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-lgxn
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr714-0075-0057-tenant/tkrw-pr714-0075-0057-app/devfile-sample-lgxn@sha256:94ac7ce86b3d68eb6936f35e9930bc5c9aeae505986fafe02f84d8eefd2c2c76
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
