apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-lgxn
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr714-0075-0057-tenant/tkrw-pr714-0075-0057-app/devfile-sample-lgxn@sha256:94ac7ce86b3d68eb6936f35e9930bc5c9aeae505986fafe02f84d8eefd2c2c76
        name: my-nodejs
        resources: {}
status: {}
